# Generated by Django 3.0.3 on 2020-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[('andhrapradesh', 'Andhrapradesh'), ('karnataka', 'Karnataka'), ('tamilnadu', 'Tamilnadu'), ('kerala', 'Kerala')], max_length=120, unique=True),
        ),
    ]
