# Generated by Django 3.0.3 on 2020-02-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200203_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
    ]
